spring:
    profiles:
        active: dev
    datasource:
            dataSourceClassName: org.h2.Driver
            url: jdbc:h2:mem:TEST1;MVCC=true;DB_CLOSE_DELAY=-1;MODE=Oracle
            databaseName:
            serverName:
            username: sa
            password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            
  
              
spring.h2.console.enabled: true

spring.h2.console.path: /h2-console


